### ISSUE TITLE
RabbitMQ in Depth

### ISSUE THREAD

**Issue by alirezaarzehgar** [alirezaarzehgar/ali#16]
Pages: 266

## PART 1 RABBITMQ AND APPLICATION ARCHITECTURE
- [ ] 1 Foundational RabbitMQ 3
- [ ] 2 How to speak Rabbit: the AMQ Protocol
- [ ] 3 An in-depth tour of message properties
- [ ] 4 Performance trade-offs in publishing
- [ ] 5 Don’t get messages; consume them
- [ ] 6 Message patterns via exchange routing
## PART 2 MANAGING RABBITMQ IN THE DATA CENTER OR THE CLOUD
- [ ] 7 Scaling RabbitMQ with clusters
- [ ] 8 Cross-cluster message distribution 148
## PART 3 INTEGRATIONS AND CUSTOMIZATION
- [ ] 9 Using alternative protocols
- [ ] 10 Database integrations

**Comment by alirezaarzehgar** [comment]
First of all I wanted to read RabbitMQ in Depth book. But that book is very hard. It's text is hard to read and it's content is very professional for me. I wont recommend that for start learning RabbitMQ. That's cool but you should spent many times for that.
Mastering X series is more fun for beginning a topic. It start with simple things and don't dig into deep contexts. After reading Mastering RabbitMQ reading RabbitMQ in Depth will be very very enjoyable!
