### ISSUE TITLE
CSS in depth

### ISSUE THREAD

**Issue by alirezaarzehgar** [alirezaarzehgar/ali#2]
# Part 1(Reviewing the fundamentals)
- [ ] Cascade, specificity, and inheritance
- [ ] Working with relative units
- [ ] Mastering the box model

# Part 2 (Mastering layout)
- [ ] Making sense of floats
- [ ] Flexbox
- [ ] Grid layout
- [ ] Positioning and stacking contexts
- [ ] Responsive design

# Part 3 (CSS at scale)
- [ ] Modular CSS
- [ ] Pattern libraries

# Part 4 (Advanced topics)
- [ ] Backgrounds, shadows, and blend modes
- [ ] Contrast, color, and spacing
- [ ] Typography
- [ ] Transitions
- [ ] Transforms
- [ ] Animations

**Comment by erfan-goodarzi** [comment]
- [ ] **CSS variables:** Using custom properties to define reusable values within a stylesheet.

- [ ] **CSS frameworks**: Learning how to use popular CSS frameworks (like Bootstrap or Foundation) to speed up and standardize your layout and design process.

**Comment by alirezaarzehgar** [comment]
> * [ ]  **CSS variables:** Using custom properties to define reusable values within a stylesheet.
> 
>     * [ ]  **CSS frameworks**: Learning how to use popular CSS frameworks (like Bootstrap or Foundation) to speed up and standardize your layout and design process.

Thanks to your reply Erfan! I'm glad for your attention.
But this `CSS in depth` is a book and this subtasks comes from topics of this book.
Anyway thanks for your suggestion. I will research about them :)

**Comment by erfan-goodarzi** [comment]
Anytime bro.
oh I didn't know about this book. I thought this is a roadmap. sorry.
